Update get.py
brain-image-library/py-brain-inventory pull request #32
Opened 2023-07-12 20:09 UTC by ManavMahida

This is what I did let me know what you think.

2023-07-13 02:48 UTC, icaoberg requested changes
Please make the requested changes and request another review when you are done.

2023-07-13 02:48 UTC, icaoberg commented on braininventory/get.py
> +df['generalmodality'].value_counts()
This is correct but I want you to do is create a function from this line. Something that looks like

```
def get_number_of_modalities(df):
    return df['generalmodality'].value_counts()
```
Though what I suggested above is accurate I would like you to

* convert your statement into a [dictionary](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html)
* Document the function.

2023-07-13 19:43 UTC, monicappaz commented
This may be helpful for you to do the documentation. If you have any questions about how to document it, ask Ivan: https://www.madcapsoftware.com/blog/write-code-documentation/#:~:text=Code%20documentation%20can%20take%20the,diagrams%2C%20writing%20API%20documentation%2C%20describing

2023-07-24 04:03 UTC, icaoberg approved these changes

2023-07-24 04:03 UTC, merged